version: '3.8'
services:
  mms:
    container_name: mssql-meilisearch-sync-1
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 7770:7770
    networks:
      - meilisearch
networks:
  meilisearch:
    driver: bridge
