export const AdhocCdcQuery =(start_lsn, pageSize )=> `SELECT TOP ${pageSize} 
    SELECT TOP (1000)
    R.[__$start_lsn] AS Response_start_lsn,
    R.[__$operation] AS Response_operation,
    R.[OID] as id,
    R.[SequenceNumber],
    R.[Type],
    R.[Priority],
    R.[HandlingResource],
    R.[Zone],
    R.[AgencyName],
    R.[DispatchGroup],
    R.[IncidentNumber],
    R.[PrimaryResponse],
    R.[DispatcherDisplayName],
    R.[DispatcherLogonName],
    R.[CreationTime],
    R.[CreationDate],
    R.[ClassificationName],
    R.[StatusTime],
    R.[IncidentCreationTime],
    R.[ResponseLocation],
    R.[RespAlarmLevel],
    R.[PrimaryResource],
    R.[MilestoneName],
    R.[OriginName],
    R.[PersonCount],
    R.[Status],
    R.[ImportDateTime],
    R.[ResponseTypeCategory],
    PT.[__$start_lsn] AS ProcessTimes_start_lsn,
    PT.[__$operation] AS ProcessTimes_operation,
    PT.[CreationTime] AS ProcessTimes_CreationTime,
    PT.[Dispatch],
    PT.[Disposition],
    PT.[Completion],
FROM [Adhoc].[cdc].[dbo_Responses_CT] AS R
LEFT JOIN [Adhoc].[cdc].[dbo_ProcessTimes_CT] AS PT ON R.[OID] = PT.[ResponseOID]
WHERE [__$start_lsn] > ${start_lsn || 0}`
